"""Auto migration

Revision ID: 5968a5e6ba6a
Revises: 8cc486e52692
Create Date: 2021-08-23 23:22:31.078214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5968a5e6ba6a'
down_revision = '8cc486e52692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='apot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='apot')
    # ### end Alembic commands ###