"""Auto migration

Revision ID: 8cc486e52692
Revises: e4ffefa76c2e
Create Date: 2021-08-23 23:22:01.406591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc486e52692'
down_revision = 'e4ffefa76c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='apot')
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='apot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='apot')
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='apot')
    # ### end Alembic commands ###